- hosts: cluster
  gather_facts: yes
  become: yes
  roles:
    - { role: docker }

- hosts: cluster
  gather_facts: yes
  become: yes
  roles:
    - { role: kubeadm }

- hosts: master
  gather_facts: yes
  become: yes
  roles:
   - { role: cluster/master }

- hosts: node
  gather_facts: yes
  become: yes
  roles:
    - { role: cluster/node }

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: calico }

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: metallb }

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: ingress-controller }
    
- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: metrics }
