---
- name: Enable br_netfilter
  shell: modprobe br_netfilter

- name: Add modules-load.d config file
  copy:
    src: modules-load.conf
    dest: /etc/modules-load.d/k8s.conf

- name: Add sysctl config file
  copy:
    src: sysctl.conf
    dest: /etc/sysctl.d/k8s.conf

- name: Reload sysctl
  shell: sysctl --system
