---
- name: Install prerequisites
  apt:
    update_cache: yes
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add gpg key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release | lower }} stable"

- name: Install docker
  apt:
    update_cache: yes
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Copy docker daemon file
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: Create docker service directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0755

- name: Enable docker service
  systemd:
    name: docker
    enabled: yes

- name: Restart docker service
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
